name: Build Windows Release (Fixed)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    
    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop
    
    - name: Create Windows Platform
      run: flutter create --platforms=windows .
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Windows Release
      run: flutter build windows --release
    
    - name: Create Release Package
      shell: powershell
      run: |
        # Create directories
        New-Item -ItemType Directory -Force -Path "dist"
        New-Item -ItemType Directory -Force -Path "dist/elasticsearch-query-helper-windows"
        
        # Copy build files
        Copy-Item -Path "build/windows/runner/Release/*" -Destination "dist/elasticsearch-query-helper-windows/" -Recurse -Force
        
        # Create README
        $readme = "Elasticsearch Query Helper - Windows Version" + "`n`n"
        $readme += "Installation:" + "`n"
        $readme += "1. Extract all files to a folder" + "`n"
        $readme += "2. Double-click elasticsearch_query_helper.exe to run" + "`n`n"
        $readme += "System Requirements:" + "`n"
        $readme += "- Windows 10 or later" + "`n"
        $readme += "- No additional dependencies required" + "`n`n"
        $readme += "Version: 1.0.0" + "`n"
        $readme += "Build Date: " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss") + "`n"
        
        $readme | Out-File -FilePath "dist/elasticsearch-query-helper-windows/README.txt" -Encoding UTF8
        
        # Create start script
        $script = "@echo off" + "`n"
        $script += "echo Starting Elasticsearch Query Helper..." + "`n"
        $script += "elasticsearch_query_helper.exe" + "`n"
        $script += "pause" + "`n"
        
        $script | Out-File -FilePath "dist/elasticsearch-query-helper-windows/start.bat" -Encoding ASCII
        
        Write-Host "Package created successfully"
        Get-ChildItem "dist/elasticsearch-query-helper-windows" -Name
        
    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: elasticsearch-query-helper-windows
        path: dist/elasticsearch-query-helper-windows/
        retention-days: 30
        
    - name: Create ZIP
      shell: powershell
      run: |
        Compress-Archive -Path "dist/elasticsearch-query-helper-windows/*" -DestinationPath "elasticsearch-query-helper-windows.zip" -Force
        Write-Host "ZIP created successfully"
        
    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: elasticsearch-query-helper-windows-zip
        path: elasticsearch-query-helper-windows.zip
        retention-days: 30